Repository codestates-seb/seb39_main_008, pull requests merged in 2022-10, with the labels that each got.

#97 Feat/responsive
  client/src/assets/styles/theme.js
  client/src/components/WriteOrEditDiaryForm.js
  client/src/components/common/Header.js
  client/src/components/common/Navbar.js
  client/src/components/common/Sidebar.js
  client/src/pages/Book.js
  client/src/pages/BookList.js
  client/src/pages/Diary.js
  client/src/pages/Gate.js
  client/src/pages/Layout.js
  client/src/pages/Main.js
  client/src/pages/People.js
  client/src/pages/Userpage.js
  client/src/pages/WriteDiary.js
Labels: 프론트엔드, 기능 추가, 기능 변경

#108 Feat : 무한스크롤 커스텀 훅 제작
  client/src/lib/useInfinityScroll.js
  client/src/pages/People.js
Labels: 기능 추가, 기능 변경, Oscar

#107 Feat/theme
  client/src/App.js
  client/src/assets/styles/GlobalStyle.js
  client/src/assets/styles/theme.js
  client/src/components/Diary/Comment.js
  client/src/components/LoginForm.js
  client/src/components/MakeorEditBookForm.js
  client/src/components/People/FilterModal.js
  client/src/components/People/PeopleFilter.js
  client/src/components/SiginupInput.js
  client/src/components/SignupForm.js
  client/src/components/WriteOrEditDiaryForm.js
  client/src/components/common/Avatar.js
  client/src/components/common/BorderButton.js
  client/src/components/common/ConfirmModal.js
  client/src/components/common/ContentCard.js
  client/src/components/common/Date.js
  client/src/components/common/DiaryCard.js
  client/src/components/common/Header.js
  client/src/components/common/Loading.js
  client/src/components/common/LoadingUnit.js
  client/src/components/common/Logo.js
  client/src/components/common/MakeButton.js
  client/src/components/common/Navbar.js
  client/src/components/common/Profile.js
  client/src/components/common/Sidebar.js
  client/src/components/common/TextButton.js
  client/src/components/common/UserCard.js
  client/src/hooks/useTheme.js
  client/src/index.js
  client/src/lib/axios.js
  client/src/lib/localStorage.js
  client/src/pages/Book.js
  client/src/pages/BookList.js
  client/src/pages/Diary.js
  client/src/pages/EditDiary.js
  client/src/pages/Error.js
  client/src/pages/Layout.js
  client/src/pages/Main.js
  client/src/pages/People.js
  client/src/pages/Signup.js
  client/src/pages/Theme.js
  client/src/pages/Userpage.js
  client/src/pages/WriteDiary.js
  client/src/pages/router.js
Labels: 프론트엔드, 기능 변경

#115 Feat/landingpage
  client/src/App.js
  client/src/assets/img/1-1.png
  client/src/assets/img/1-2.png
  client/src/assets/img/1-3.png
  client/src/assets/img/1-4.png
  client/src/assets/img/Macbook.png
  client/src/assets/img/iPad.png
  client/src/assets/img/iPhone.png
  client/src/assets/img/user1.png
  client/src/assets/img/user2.png
  client/src/assets/img/user3.png
  client/src/assets/img/user4.png
  client/src/pages/Landing.js
  client/src/pages/router.js
Labels: 프론트엔드, Feature

#116 Feat/swan refactor
  client/src/App.js
  client/src/assets/logo.svg
  client/src/components/common/ContentCard.js
  client/src/components/common/MakeButton.js
  client/src/components/common/Navbar.js
  client/src/components/common/Sidebar.js
  client/src/lib/axios.js
  client/src/mocks/dummyData.js
  client/src/mocks/handlers.js
  client/src/pages/Book.js
  client/src/pages/BookList.js
  client/src/pages/Diary.js
  client/src/pages/Landing.js
  client/src/pages/Layout.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/People.js
  client/src/pages/Signup.js
Labels: 프론트엔드, Feature

#117 Feat/swan refactor
  client/src/components/WriteOrEditDiaryForm.js
  client/src/components/common/Avatar.js
  client/src/components/common/ConfirmModal.js
  client/src/components/common/Navbar.js
  client/src/components/common/Sidebar.js
  client/src/pages/Diary.js
  client/src/pages/Layout.js
  client/src/pages/Userpage.js
Labels: bug, 기능 변경
