Repository codestates-seb/seb39_main_008, pull requests merged in 2022-09, with the labels that each got.

#22 Feat : Set up client
  client/.eslintrc.json
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/mockServiceWorker.js
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.tsx
  client/src/Router.tsx
  client/src/assets/img/signinImg.png
  client/src/assets/logo.svg
  client/src/assets/styles/GlobalStyle.js
  client/src/assets/styles/theme.js
  client/src/components/common/ComfirmModal.js
  client/src/components/common/ContentCard.js
  client/src/components/common/Header.js
  client/src/components/common/Loading.js
  client/src/components/common/Profile.js
  client/src/components/common/Sidebar.js
  client/src/components/common/TextButton.js
  client/src/components/common/UserCard.js
  client/src/index.css
  client/src/index.js
  client/src/index.tsx
  client/src/lib/axios.js
  client/src/mocks/browser.js
  client/src/mocks/handlers.js
  client/src/pages/Book.js
  client/src/pages/BookList.js
  client/src/pages/Diary.js
  client/src/pages/Error.js
  client/src/pages/Gate.js
  client/src/pages/Landing.js
  client/src/pages/Main.js
  client/src/pages/MakeBook.js
  client/src/pages/Oscar.tsx
  client/src/pages/People.js
  client/src/pages/Root.js
  client/src/pages/Signin.js
  client/src/pages/Swan.tsx
  client/src/pages/Userpage.js
  client/src/pages/WriteDiary.js
  client/src/react-app-env.d.ts
  client/src/redux/slices/userSlice.js
  client/src/redux/store/store.js
  client/src/types/user.ts
  client/tsconfig.json
Labels: 프론트엔드

#25 Feat/button
  client/public/index.html
  client/src/assets/styles/GlobalStyle.js
  client/src/assets/styles/theme.js
  client/src/components/common/TextButton.js
Labels: 프론트엔드, 기능 추가, 기능 변경, Feature

#31 Feat/loading
  client/src/assets/styles/theme.js
  client/src/components/common/Loading.js
  client/src/components/common/Logo.js
Labels: 프론트엔드, 기능 추가, 기능 변경, Feature

#32 Feat : Write get methods for members, diaries, and books
  client/src/App.js
  client/src/mocks/dummyData.js
  client/src/mocks/handlers.js
Labels: 프론트엔드, 기능 추가, Feature

#33 Feal/signin
  client/src/App.css
  client/src/assets/styles/GlobalStyle.js
  client/src/assets/styles/theme.js
  client/src/components/common/TextButton.js
  client/src/index.css
  client/src/pages/Signin.js
Labels: 프론트엔드, 기능 추가, Feature

#36 Chore : Modify background img path
  client/src/pages/Signin.js
Labels: 프론트엔드

#35 Feat/layout
  client/src/App.js
  client/src/components/common/Header.js
  client/src/components/common/Sidebar.js
  client/src/pages/Layout.js
Labels: 프론트엔드, 기능 추가, 기능 변경, Feature

#37 Feat : Add avatar component
  client/src/App.js
  client/src/components/common/Avatar.js
  client/src/components/common/Logo.js
  client/src/components/common/Sidebar.js
Labels: 프론트엔드, 기능 추가, 기능 변경, Feature

#39 Feat/sidebar
  client/src/assets/styles/theme.js
  client/src/components/common/Sidebar.js
Labels: 프론트엔드, Feature

#40 Feal/signin
  client/src/components/common/TextButton.js
  client/src/pages/Signin.js
Labels: 프론트엔드, 기능 변경, Feature

#44 Feat : profile, usercard 컴포넌트 작성
  client/src/components/common/Profile.js
  client/src/components/common/UserCard.js
  client/src/mocks/dummyData.js
Labels: 프론트엔드, 기능 추가, 기능 변경, Oscar, Feature

#47 Feat/sidebar
  client/src/components/common/ComfirmModal.js
  client/src/components/common/Sidebar.js
Labels: 프론트엔드, 기능 추가, Feature

#48 Chore : 공통 컴포넌트 없는 경우 레이아웃 변경
  client/src/components/common/Header.js
  client/src/pages/Layout.js
  client/src/pages/Signin.js
Labels: 프론트엔드, 기능 변경, Feature

#52 Comment : import 구문 주석 추가
  client/src/pages/OAuth2Redirect.js
Labels: bug, 프론트엔드

#53 Feat : 사람들 페이지 기능 마크업, 디자인, 기능 개발
  client/src/components/common/UserCard.js
  client/src/pages/Layout.js
  client/src/pages/People.js
Labels: 기능 추가, 기능 변경, Oscar, Feature

#55 Feat/content card
  client/src/assets/styles/theme.js
  client/src/components/common/ContentCard.js
  client/src/components/common/Date.js
  client/src/components/common/Logo.js
  client/src/components/common/MakeButton.js
  client/src/lib/axios.js
Labels: 프론트엔드, 기능 추가

#56 Chore : 로딩컴포넌트 세부화
  client/src/components/common/Loading.js
  client/src/components/common/LoadingUnit.js
Labels: 프론트엔드, 기능 변경, Oscar

#58 Feat : 텍스트 에디터 추가
  client/src/components/TextEditor.js
Labels: 프론트엔드, 기능 추가

#63 Feat/signin
  client/package.json
  client/src/App.js
  client/src/components/LoginForm.js
  client/src/components/SignupForm.js
  client/src/components/common/BorderButton.js
  client/src/components/common/Input.js
  client/src/components/common/Sidebar.js
  client/src/components/common/TextButton.js
  client/src/pages/Login.js
  client/src/pages/Signin.js
  client/src/pages/Signup.js
Labels: 프론트엔드, 기능 추가, Feature

#65 Feat/signin
  client/src/components/LoginForm.js
  client/src/components/SiginupInput.js
  client/src/components/SignupForm.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: 프론트엔드

#64 Feat: 사람들 페이지 필터링 기능 및 디자인 완성
  client/src/components/People/FilterModal.js
  client/src/components/People/PeopleFilter.js
  client/src/pages/People.js
Labels: 기능 추가, 기능 변경, Oscar, Feature

#67 Feat : mainpage에 글목록 추가
  client/src/pages/Main.js
Labels: 프론트엔드, 기능 추가, Feature

#73 Feat: 목업서버 데이터 및 로직 변경
  client/src/components/common/UserCard.js
  client/src/mocks/dummyData.js
  client/src/mocks/handlers.js
  client/src/pages/People.js
  client/src/pages/Userpage.js
Labels: 기능 추가, 기능 변경, Oscar, Feature

#76 Feat/writediary
  client/src/components/TextEditor.js
  client/src/components/WriteOrEditDiaryForm.js
  client/src/components/common/ConfirmModal.js
  client/src/components/common/ImageInput.js
  client/src/components/common/Sidebar.js
  client/src/pages/WriteDiary.js
Labels: 프론트엔드, 기능 추가, Feature

#78 Feat/makebook
  client/src/components/MakeorEditBookForm.js
  client/src/components/WriteOrEditDiaryForm.js
  client/src/pages/MakeBook.js
Labels: 프론트엔드, 기능 추가, Feature

#80 Feat : main page 레이아웃 작업
  client/src/components/common/ContentCard.js
  client/src/components/common/Thumbnail.js
  client/src/components/common/UserCard.js
  client/src/mocks/handlers.js
  client/src/pages/Main.js
Labels: 기능 추가, 기능 변경, Oscar

#83 Feat/comment
  client/src/components/Diary/Comment.js
  client/src/components/common/Sidebar.js
Labels: 프론트엔드, 기능 추가, Feature

#85 Feat : Userpage 레이아웃 완성 및 diarycard 컴포넌트 추가
  client/src/components/common/DiaryCard.js
  client/src/pages/Userpage.js
Labels: 기능 추가, 기능 변경, Oscar, Feature

#87 Feat/editdiary
  client/src/App.js
  client/src/components/TextEditor.js
  client/src/components/WriteOrEditDiaryForm.js
  client/src/lib/axios.js
  client/src/pages/Diary.js
  client/src/pages/EditBook.js
  client/src/pages/EditDiary.js
  client/src/pages/OAuth2Redirect.js
  client/src/pages/router.js
Labels: 프론트엔드, 기능 추가, 기능 변경, Feature

#89 Feat/booklist
  client/src/components/common/ContentCard.js
  client/src/pages/BookList.js
  client/src/pages/Main.js
Labels: 프론트엔드, 기능 추가, Feature

#92 Feat/bookpage
  client/src/lib/axios.js
  client/src/pages/Book.js
  client/src/pages/Layout.js
Labels: 프론트엔드, 기능 추가
